-- Sennara — Egyptian Fish Species Seed
-- Run after applying 001_initial_schema.sql

INSERT INTO species (
    scientific_name,
    english_name,
    arabic_name,
    egyptian_slang_names,
    family,
    category,
    water_bodies,
    description,
    habitat,
    average_weight_kg,
    conservation_status
) VALUES
(
    'Sparus aurata',
    'Gilthead Seabream',
    'دنيس',
    ARRAY['Denise', 'Denis', 'دنيس'],
    'Sparidae',
    'demersal',
    ARRAY['mediterranean_sea', 'red_sea'],
    'One of the most prized Mediterranean table fish in Egypt. Caught around reefs and rocky bottoms.',
    'Rocky bottoms, reefs, seagrass beds up to 150m depth.',
    1.200,
    'least_concern'
),
(
    'Dicentrarchus labrax',
    'European Seabass',
    'قاروص',
    ARRAY['Qarous', 'Qarous', 'قاروص'],
    'Moronidae',
    'demersal',
    ARRAY['mediterranean_sea', 'red_sea'],
    'Highly valued sport and commercial fish. Active predator near shorelines and estuaries.',
    'Coastal waters, estuaries, lagoons; often near structures.',
    2.500,
    'least_concern'
),
(
    'Lethrinus nebulosus',
    'Spangled Emperor',
    'شعور',
    ARRAY['Sohor', 'Sho''oor', 'شعور'],
    'Lethrinidae',
    'demersal',
    ARRAY['red_sea', 'gulf_of_suez', 'gulf_of_aqaba'],
    'A Red Sea favorite, known locally as Sohor or Sho''oor. Strong fighter on light tackle.',
    'Coral reefs, sandy flats, seagrass beds from 1-185m.',
    3.000,
    'least_concern'
),
(
    'Epinephelus coioides',
    'Orange-spotted Grouper',
    'هامور',
    ARRAY['Hamour', 'Hamour', 'هامور'],
    'Serranidae',
    'demersal',
    ARRAY['red_sea', 'gulf_of_suez', 'gulf_of_aqaba'],
    'The iconic Hamour. Ambush predator of the Red Sea, highly prized for its firm white flesh.',
    'Coral reefs, rocky bottoms, turbid coastal waters.',
    8.000,
    'near_threatened'
),
(
    'Oreochromis niloticus',
    'Nile Tilapia',
    'بلطي',
    ARRAY['Bolty', 'Tilapia', 'بلطي'],
    'Cichlidae',
    'freshwater',
    ARRAY['nile_river', 'lake_nasser'],
    'Egypt''s most important freshwater farmed and wild-caught fish. Mild flavor and firm texture.',
    'Rivers, lakes, irrigation canals, warm shallow fresh water.',
    0.500,
    'least_concern'
),
(
    'Solea solea',
    'Common Sole',
    'سمك موسى',
    ARRAY['Samak Moussa', 'Moussa Fish', 'سمك موسى'],
    'Soleidae',
    'demersal',
    ARRAY['mediterranean_sea'],
    'Flatfish lying on sandy bottoms. Locally called Samak Moussa. Delicate texture.',
    'Sandy and muddy bottoms in coastal waters.',
    1.000,
    'least_concern'
),
(
    'Mugil cephalus',
    'Flathead Grey Mullet',
    'بوري',
    ARRAY['Bouri', 'Bori', 'بوري'],
    'Mugilidae',
    'brackish',
    ARRAY['mediterranean_sea', 'nile_river', 'manzala_lagoon', 'burullus_lagoon'],
    'Found in coastal waters, lagoons and the Nile Delta. Popular in salted/fried preparations.',
    'Estuaries, lagoons, coastal marine waters.',
    1.500,
    'least_concern'
),
(
    'Pagellus erythrinus',
    'Common Pandora',
    'شرغوط',
    ARRAY['Shergoat', 'Shargout', 'شرغوط'],
    'Sparidae',
    'demersal',
    ARRAY['mediterranean_sea', 'red_sea'],
    'Pinkish seabream common in Egyptian waters. Good eating and easy to catch on cut bait.',
    'Sandy and muddy bottoms from 20-250m.',
    0.800,
    'least_concern'
),
(
    'Mullus surmuletus',
    'Striped Red Mullet',
    'سلطان إبراهيم',
    ARRAY['Sultan Ibrahim', 'Sultan', 'سلطان إبراهيم'],
    'Mullidae',
    'demersal',
    ARRAY['mediterranean_sea', 'red_sea'],
    'Small but beloved table fish, often fried whole. Distinctive barbels under the chin.',
    'Sandy and muddy bottoms, often buried during the day.',
    0.300,
    'least_concern'
),
(
    'Siganus rivulatus',
    'Marbled Spinefoot',
    'أرنب',
    ARRAY['Araneb', 'Rabbitfish', 'أرنب'],
    'Siganidae',
    'herbivorous_reef',
    ARRAY['red_sea', 'gulf_of_suez', 'gulf_of_aqaba'],
    'Called Araneb (rabbit) for its snout shape. Watch out for venomous dorsal spines.',
    'Shallow coral reefs, seagrass beds, rocky shores.',
    0.400,
    'least_concern'
),
(
    'Thunnus albacares',
    'Yellowfin Tuna',
    'تونة صفراء الزعانف',
    ARRAY['Tuna', 'Yellowfin', 'تونة'],
    'Scombridae',
    'pelagic',
    ARRAY['red_sea', 'gulf_of_aqaba'],
    'Offshore predator targeted by trolling. Powerful runs and deep dives.',
    'Open ocean, often associated with temperature fronts and floating objects.',
    40.000,
    'near_threatened'
),
(
    'Caranx sexfasciatus',
    'Bigeye Trevally',
    'فرس النبي',
    ARRAY['Faras El Nabi', 'Trevally', 'فرس النبي'],
    'Carangidae',
    'pelagic',
    ARRAY['red_sea', 'gulf_of_suez'],
    'Fast schooling predator around reefs and wrecks. Excellent sport on poppers and jigs.',
    'Coral reefs, offshore islands, wrecks.',
    3.500,
    'least_concern'
),
(
    'Lates niloticus',
    'Nile Perch',
    'قشر البياض',
    ARRAY['Qishr El-Bayad', 'Nile Perch', 'قشر البياض'],
    'Latidae',
    'freshwater',
    ARRAY['lake_nasser', 'nile_river'],
    'Giant predator of Lake Nasser. Reaches enormous sizes and is the ultimate freshwater trophy.',
    'Deep open water in large lakes and rivers.',
    25.000,
    'least_concern'
),
(
    'Bagrus bajad',
    'Bayad',
    'بطاط',
    ARRAY['Bayad', 'Batat', 'بطاط'],
    'Bagridae',
    'freshwater',
    ARRAY['nile_river', 'lake_nasser'],
    'Large catfish of the Nile and Lake Nasser. Nocturnal bottom feeder.',
    'Deep river channels and lake bottoms.',
    10.000,
    'least_concern'
),
(
    'Arius heudelotii',
    'African Sea Catfish',
    'قرموط',
    ARRAY['Qarmout', 'Sea Catfish', 'قرموط'],
    'Ariidae',
    'brackish',
    ARRAY['mediterranean_sea', 'nile_river', 'manzala_lagoon', 'burullus_lagoon'],
    'Catfish found in brackish coastal waters and lagoons. Hard fighter.',
    'Estuaries, lagoons, shallow coastal waters.',
    3.000,
    'least_concern'
)
ON CONFLICT (scientific_name) DO UPDATE SET
    english_name = EXCLUDED.english_name,
    arabic_name = EXCLUDED.arabic_name,
    egyptian_slang_names = EXCLUDED.egyptian_slang_names,
    family = EXCLUDED.family,
    category = EXCLUDED.category,
    water_bodies = EXCLUDED.water_bodies,
    description = EXCLUDED.description,
    habitat = EXCLUDED.habitat,
    average_weight_kg = EXCLUDED.average_weight_kg,
    conservation_status = EXCLUDED.conservation_status,
    updated_at = NOW();
